import { Property, Testimonial } from './types';

// ========== DEMO PROPERTIES ==========
// These will be replaced with real data from Excel later

export const DEMO_PROPERTIES: Property[] = [
  {
    id: 'prop-001',
    title: 'Residencia Premium Campestre',
    type: 'casa',
    price: 4500000,
    currency: 'MXN',
    location: 'Campestre, Ciudad Juárez',
    colonia: 'Campestre',
    address: 'Av. Campestre #456, Col. Campestre',
    sqMeters: 320,
    bedrooms: 4,
    bathrooms: 3,
    parking: 3,
    description: 'Espectacular residencia en una de las zonas más exclusivas de Ciudad Juárez. Diseño arquitectónico moderno con acabados de primera calidad. Amplia sala-comedor con doble altura y ventanales panorámicos que llenan el espacio de luz natural. Cocina integral con isla central, electrodomésticos de acero inoxidable y acabados en granito. Recámaras amplias con walk-in closets, baños completos con mármol. Jardín trasero con terraza y área de asador. Sistema de seguridad con cámaras y acceso controlado.',
    shortDescription: 'Residencia de lujo con acabados premium, 4 recámaras, jardín y terraza en zona exclusiva.',
    images: [
      'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&q=80',
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&q=80',
    ],
    amenities: ['Jardín', 'Terraza', 'Cocina Integral', 'Doble Altura', 'Seguridad 24/7', 'Estacionamiento Techado'],
    status: 'activa',
    featured: true,
    yearBuilt: 2023,
    floors: 2,
    lat: 31.6904,
    lng: -106.4245,
    createdAt: Date.now() - 86400000 * 5,
    updatedAt: Date.now(),
  },
  {
    id: 'prop-002',
    title: 'Casa Moderna Las Misiones',
    type: 'casa',
    price: 3200000,
    currency: 'MXN',
    location: 'Las Misiones, Ciudad Juárez',
    colonia: 'Las Misiones',
    address: 'Calle Misioneros #123, Las Misiones',
    sqMeters: 240,
    bedrooms: 3,
    bathrooms: 2,
    parking: 2,
    description: 'Casa moderna con diseño minimalista en fraccionamiento cerrado con seguridad 24/7. Sala amplia con chimenea, comedor independiente, cocina integral equipada. Recámara principal con vestidor y baño completo. Patio trasero con área verde y posibilidad de alberca. Excelente ubicación cerca de centros comerciales, escuelas y vías principales.',
    shortDescription: 'Casa moderna en fraccionamiento cerrado, 3 recámaras, excelente ubicación.',
    images: [
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80',
      'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&q=80',
      'https://images.unsplash.com/photo-1600573472550-8090b5e0745e?w=800&q=80',
    ],
    amenities: ['Fraccionamiento Cerrado', 'Chimenea', 'Cocina Integral', 'Patio', 'Seguridad 24/7'],
    status: 'activa',
    featured: true,
    yearBuilt: 2022,
    floors: 2,
    lat: 31.7280,
    lng: -106.4560,
    createdAt: Date.now() - 86400000 * 10,
    updatedAt: Date.now(),
  },
  {
    id: 'prop-003',
    title: 'Departamento Vista Campos Elíseos',
    type: 'departamento',
    price: 2100000,
    currency: 'MXN',
    location: 'Campos Elíseos, Ciudad Juárez',
    colonia: 'Campos Elíseos',
    address: 'Blvd. Campos Elíseos #789, Torre Norte Piso 8',
    sqMeters: 130,
    bedrooms: 2,
    bathrooms: 2,
    parking: 1,
    description: 'Departamento de lujo en torre premium de Campos Elíseos con una vista impresionante de la ciudad. Acabados de alta gama, piso de porcelanato, cocina integral con electrodomésticos incluidos. Amenidades del edificio: gimnasio, alberca, salón de eventos, roof garden, seguridad con vigilancia 24/7 y control de acceso biométrico.',
    shortDescription: 'Departamento de lujo con vista panorámica, amenidades premium en torre exclusiva.',
    images: [
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80',
    ],
    amenities: ['Gimnasio', 'Alberca', 'Roof Garden', 'Elevador', 'Vigilancia 24/7', 'Control Biométrico'],
    status: 'activa',
    featured: true,
    yearBuilt: 2024,
    floors: 1,
    lat: 31.7100,
    lng: -106.4380,
    createdAt: Date.now() - 86400000 * 3,
    updatedAt: Date.now(),
  },
  {
    id: 'prop-004',
    title: 'Terreno Comercial Gómez Morín',
    type: 'terreno',
    price: 5000000,
    currency: 'MXN',
    location: 'Gómez Morín, Ciudad Juárez',
    colonia: 'Gómez Morín',
    address: 'Paseo Triunfo de la República, Gómez Morín',
    sqMeters: 800,
    bedrooms: 0,
    bathrooms: 0,
    parking: 0,
    description: 'Terreno comercial en una de las avenidas más transitadas de Ciudad Juárez. Ideal para plaza comercial, corporativo, restaurante o desarrollo mixto. Frente de 25 metros sobre avenida principal. Uso de suelo comercial aprobado. Servicios completos (agua, luz, drenaje). Excelente plusvalía con crecimiento del 12% anual en la zona.',
    shortDescription: 'Terreno comercial sobre avenida principal, ideal para desarrollo o plaza comercial.',
    images: [
      'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&q=80',
      'https://images.unsplash.com/photo-1416339306562-f3d12fefd36f?w=800&q=80',
    ],
    amenities: ['Uso Comercial', 'Servicios Completos', 'Frente a Avenida', 'Alta Plusvalía'],
    status: 'activa',
    featured: false,
    lat: 31.7350,
    lng: -106.4400,
    createdAt: Date.now() - 86400000 * 15,
    updatedAt: Date.now(),
  },
  {
    id: 'prop-005',
    title: 'Casa Inversión Sierra Vista',
    type: 'inversion',
    price: 1800000,
    currency: 'MXN',
    location: 'Sierra Vista, Ciudad Juárez',
    colonia: 'Sierra Vista',
    address: 'Calle Sierra Madre #567, Sierra Vista',
    sqMeters: 180,
    bedrooms: 3,
    bathrooms: 2,
    parking: 2,
    description: 'Excelente oportunidad de inversión. Casa en zona de alta demanda de renta. Actualmente rentada con ingreso mensual de $12,000 MXN. ROI estimado del 8% anual. Zona residencial tranquila, cerca de escuelas y supermercados. Casa en excelente estado, mantenimiento reciente. Ideal para inversionistas que buscan rendimiento seguro.',
    shortDescription: 'Oportunidad de inversión con ROI del 8% anual, rentada actualmente en $12,000/mes.',
    images: [
      'https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=800&q=80',
      'https://images.unsplash.com/photo-1554995207-c18c203602cb?w=800&q=80',
    ],
    amenities: ['Rentada', 'Alto ROI', 'Zona Tranquila', 'Bien Mantenida', 'Cercana a Servicios'],
    status: 'activa',
    featured: true,
    yearBuilt: 2019,
    floors: 1,
    lat: 31.7150,
    lng: -106.4100,
    createdAt: Date.now() - 86400000 * 7,
    updatedAt: Date.now(),
  },
  {
    id: 'prop-006',
    title: 'Local Comercial Pronaf',
    type: 'comercial',
    price: 2800000,
    currency: 'MXN',
    location: 'Pronaf, Ciudad Juárez',
    colonia: 'Pronaf',
    address: 'Av. Lincoln #345, Zona Pronaf',
    sqMeters: 200,
    bedrooms: 0,
    bathrooms: 2,
    parking: 4,
    description: 'Local comercial en excelente ubicación dentro de la zona Pronaf, una de las áreas de mayor tráfico peatonal y vehicular de Ciudad Juárez. Espacio abierto con posibilidad de dividir. Ideal para restaurante, oficinas corporativas, clínica o showroom. Estacionamiento propio para 4 vehículos. Fachada con vitrina amplia y visibilidad desde la avenida.',
    shortDescription: 'Local comercial en zona Pronaf con alta visibilidad y estacionamiento propio.',
    images: [
      'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&q=80',
      'https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=800&q=80',
    ],
    amenities: ['Alta Visibilidad', 'Estacionamiento Propio', 'Vitrina Amplia', 'Zona Comercial', 'Servicios Completos'],
    status: 'activa',
    featured: false,
    lat: 31.7200,
    lng: -106.4350,
    createdAt: Date.now() - 86400000 * 20,
    updatedAt: Date.now(),
  },
  {
    id: 'prop-007',
    title: 'Residencia Nogales Grand',
    type: 'casa',
    price: 3800000,
    currency: 'MXN',
    location: 'Nogales, Ciudad Juárez',
    colonia: 'Nogales',
    address: 'Calle Nogal #890, Col. Nogales',
    sqMeters: 280,
    bedrooms: 4,
    bathrooms: 3,
    parking: 2,
    description: 'Hermosa residencia en Col. Nogales con arquitectura contemporánea. Amplios espacios, sala con chimenea de doble frente, comedor formal, family room. Cocina de lujo con isla y barra de granito. Recámara principal tipo suite con jacuzzi. Jardín trasero con alberca climatizada y terraza con pérgola. Sistema domótico inteligente con control de iluminación y seguridad.',
    shortDescription: 'Residencia contemporánea con alberca climatizada y sistema domótico inteligente.',
    images: [
      'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&q=80',
      'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800&q=80',
      'https://images.unsplash.com/photo-1583608205776-bfd35f0d9f83?w=800&q=80',
    ],
    amenities: ['Alberca Climatizada', 'Domótica', 'Chimenea', 'Jacuzzi', 'Pérgola', 'Cocina de Lujo'],
    status: 'activa',
    featured: true,
    yearBuilt: 2021,
    floors: 2,
    lat: 31.7050,
    lng: -106.4500,
    createdAt: Date.now() - 86400000 * 12,
    updatedAt: Date.now(),
  },
  {
    id: 'prop-008',
    title: 'Departamento Quintas del Valle',
    type: 'departamento',
    price: 1400000,
    currency: 'MXN',
    location: 'Quintas del Valle, Ciudad Juárez',
    colonia: 'Quintas del Valle',
    address: 'Av. del Valle #234, Ed. Quintas P.B.',
    sqMeters: 95,
    bedrooms: 2,
    bathrooms: 1,
    parking: 1,
    description: 'Departamento ideal para pareja joven o inversión. Ubicado en zona de alta demanda de renta estudiantil y profesional. Sala-comedor-cocina integrada con diseño funcional. Dos recámaras con closets amplios. Baño completo con acabados modernos. Excelente acceso a transporte público y centros comerciales. Cuota de mantenimiento muy accesible.',
    shortDescription: 'Departamento funcional, ideal para inversión o primera vivienda.',
    images: [
      'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800&q=80',
      'https://images.unsplash.com/photo-1536376072261-38c75010e6c9?w=800&q=80',
    ],
    amenities: ['Céntrico', 'Transporte Cercano', 'Mantenimiento Bajo', 'Closets Amplios'],
    status: 'activa',
    featured: false,
    yearBuilt: 2020,
    floors: 1,
    lat: 31.6950,
    lng: -106.4150,
    createdAt: Date.now() - 86400000 * 8,
    updatedAt: Date.now(),
  },
  {
    id: 'prop-009',
    title: 'Terreno Residencial Bosques del Valle',
    type: 'terreno',
    price: 1200000,
    currency: 'MXN',
    location: 'Bosques del Valle, Ciudad Juárez',
    colonia: 'Bosques del Valle',
    address: 'Calle Encinos Lote 15, Bosques del Valle',
    sqMeters: 350,
    bedrooms: 0,
    bathrooms: 0,
    parking: 0,
    description: 'Terreno residencial en fraccionamiento Bosques del Valle. Zona en crecimiento con alta plusvalía. Apto para construir residencia de hasta 3 niveles. Todos los servicios disponibles. Fraccionamiento con caseta de vigilancia y áreas verdes comunes. Excelente oportunidad para construir tu hogar a medida.',
    shortDescription: 'Terreno residencial con servicios en fraccionamiento con vigilancia.',
    images: [
      'https://images.unsplash.com/photo-1628624747186-a941c476b7ef?w=800&q=80',
    ],
    amenities: ['Fraccionamiento con Vigilancia', 'Servicios Completos', 'Alta Plusvalía', 'Áreas Verdes'],
    status: 'activa',
    featured: false,
    lat: 31.7400,
    lng: -106.4200,
    createdAt: Date.now() - 86400000 * 25,
    updatedAt: Date.now(),
  },
  {
    id: 'prop-010',
    title: 'Casa Familiar Partido Romero',
    type: 'casa',
    price: 2400000,
    currency: 'MXN',
    location: 'Partido Romero, Ciudad Juárez',
    colonia: 'Partido Romero',
    address: 'Calle Romero #678, Partido Romero',
    sqMeters: 200,
    bedrooms: 3,
    bathrooms: 2,
    parking: 2,
    description: 'Casa familiar en excelente estado, ubicada en una de las colonias más tradicionales y seguras de Ciudad Juárez. Sala amplia con acabados de cantera, comedor independiente, cocina remodelada con barra desayunadora. Recámaras amplias con ventanas al jardín. Patio trasero con asador de ladrillo y área de lavado techada. Cochera para dos autos.',
    shortDescription: 'Casa familiar remodelada con patio, asador y cochera doble.',
    images: [
      'https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?w=800&q=80',
      'https://images.unsplash.com/photo-1600585154363-67eb9e2e2099?w=800&q=80',
    ],
    amenities: ['Remodelada', 'Asador', 'Patio', 'Cochera Doble', 'Zona Tranquila'],
    status: 'activa',
    featured: false,
    yearBuilt: 2015,
    floors: 1,
    lat: 31.6800,
    lng: -106.4300,
    createdAt: Date.now() - 86400000 * 14,
    updatedAt: Date.now(),
  },
  {
    id: 'prop-011',
    title: 'Penthouse Campos Elíseos',
    type: 'departamento',
    price: 4200000,
    currency: 'MXN',
    location: 'Campos Elíseos, Ciudad Juárez',
    colonia: 'Campos Elíseos',
    address: 'Torre Élite, Campos Elíseos, Penthouse 2',
    sqMeters: 250,
    bedrooms: 3,
    bathrooms: 3,
    parking: 2,
    description: 'Penthouse de ultra-lujo con terraza privada y vista panorámica de 270°. Acabados importados de Italia, piso de mármol Carrara, cocina Snaidero con electrodomésticos Miele. Sala-comedor con doble altura y chimenea. Baños con tina de hidromasaje. Terraza con jacuzzi exterior, área de lounge y cocina al aire libre. Incluye 2 cajones de estacionamiento con cargador para auto eléctrico. Bodega privada.',
    shortDescription: 'Penthouse de ultra-lujo con terraza privada, jacuzzi y vista de 270°.',
    images: [
      'https://images.unsplash.com/photo-1600607687644-c7171b42498f?w=800&q=80',
      'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=800&q=80',
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80',
    ],
    amenities: ['Terraza Privada', 'Jacuzzi', 'Acabados Importados', 'Cocina Snaidero', 'Cargador EV', 'Vista 270°'],
    status: 'activa',
    featured: true,
    yearBuilt: 2025,
    floors: 1,
    lat: 31.7120,
    lng: -106.4400,
    createdAt: Date.now() - 86400000 * 2,
    updatedAt: Date.now(),
  },
  {
    id: 'prop-012',
    title: 'Nave Industrial Valle del Sol',
    type: 'comercial',
    price: 8500000,
    currency: 'MXN',
    location: 'Valle del Sol, Ciudad Juárez',
    colonia: 'Valle del Sol',
    address: 'Parque Industrial Valle del Sol, Nave 8',
    sqMeters: 1200,
    bedrooms: 0,
    bathrooms: 4,
    parking: 10,
    description: 'Nave industrial en parque industrial con todas las certificaciones. Área de producción de 900m², oficinas administrativas de 300m². Andén de carga para tráiler. Instalación eléctrica trifásica. Cisterna de 10,000 litros. Sistema contra incendios. Ideal para maquiladora, almacén o centro de distribución. Cerca de cruces internacionales.',
    shortDescription: 'Nave industrial certificada con oficinas, andén de carga y 1,200 m².',
    images: [
      'https://images.unsplash.com/photo-1565610222536-ef125c59da2e?w=800&q=80',
      'https://images.unsplash.com/photo-1553877522-43269d4ea984?w=800&q=80',
    ],
    amenities: ['Andén de Carga', 'Trifásica', 'Contra Incendios', 'Cisterna', 'Oficinas', 'Estacionamiento Amplio'],
    status: 'activa',
    featured: false,
    lat: 31.7500,
    lng: -106.4600,
    createdAt: Date.now() - 86400000 * 30,
    updatedAt: Date.now(),
  },
];

// ========== DEMO TESTIMONIALS ==========

export const DEMO_TESTIMONIALS: Testimonial[] = [
  {
    id: 'test-001',
    name: 'María Elena Rodríguez',
    role: 'Compradora | Campestre',
    text: 'Gracias a OHB encontramos nuestra casa soñada en Campestre. El proceso fue transparente y profesional de principio a fin. La asesora nos guió en cada paso del crédito Infonavit y negociación.',
    rating: 5,
  },
  {
    id: 'test-002',
    name: 'Carlos Mendoza',
    role: 'Inversionista | Portafolio de 5 propiedades',
    text: 'He adquirido 5 propiedades a través de OHB en los últimos 3 años. Su análisis de ROI y conocimiento del mercado juarense me han generado rendimientos superiores al 10% anual. Sin duda los mejores asesores de la ciudad.',
    rating: 5,
  },
  {
    id: 'test-003',
    name: 'Ana Patricia Fuentes',
    role: 'Vendedora | Sierra Vista',
    text: 'Necesitaba vender mi propiedad rápido y OHB lo logró en menos de 45 días. Su estrategia de marketing digital y red de contactos hicieron la diferencia. Obtuve un precio justo y el proceso legal fue impecable.',
    rating: 5,
  },
  {
    id: 'test-004',
    name: 'Roberto Sánchez',
    role: 'Comprador de primera vivienda',
    text: 'Como comprador primerizo estaba nervioso, pero el equipo de OHB me explicó todo con paciencia. Me ayudaron con la precalificación, eligieron la mejor opción de crédito y me acompañaron hasta la firma. ¡100% recomendados!',
    rating: 5,
  },
  {
    id: 'test-005',
    name: 'Lupita Hernández',
    role: 'Inversionista | Departamentos en renta',
    text: 'La asesoría de inversiones de OHB me ayudó a construir un portafolio de departamentos que me genera ingresos pasivos constantes. Su plataforma con calculadoras y análisis de mercado es increíble.',
    rating: 5,
  },
];

// ========== UTILITY FUNCTIONS ==========

export function formatPrice(price: number): string {
  return new Intl.NumberFormat('es-MX', {
    style: 'currency',
    currency: 'MXN',
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(price);
}

export function getPropertyTypeIcon(type: Property['type']): string {
  const icons: Record<Property['type'], string> = {
    casa: '🏠',
    departamento: '🏢',
    terreno: '🌍',
    comercial: '🏪',
    inversion: '📈',
  };
  return icons[type] || '🏠';
}

export function getWhatsAppLink(propertyTitle?: string): string {
  const baseUrl = 'https://wa.me/526561327685';
  const message = propertyTitle
    ? `Hola, me interesa la propiedad "${propertyTitle}". ¿Podemos agendar una visita?`
    : 'Hola OHB, me gustaría recibir asesoría inmobiliaria. ¿Podrían contactarme?';
  return `${baseUrl}?text=${encodeURIComponent(message)}`;
}
